import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SideBar } from "./dashboard/components/nav";
import { Providers } from "@/store/provider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} h-auto bg-background-light text-inter antialiased`}
      >
        <Providers>
        <div className="flex flex-1 min-h-screen">
          
          <SideBar />

          <main className="flex-1 p-8 flex flex-col gap-6">
            {children}
          </main>
        </div>
        </Providers>
      </body>
    </html>
  );
}
